#!/usr/bin/env php
<?php

/** Static invariants for the dependency-free ProcessWire admin workspace. */

function cockpitAdminUiFail(string $message): void {
	fwrite(STDERR, "FAIL: {$message}\n");
	exit(1);
}

$root = dirname(__DIR__);
$process = file_get_contents($root . '/ProcessCockpit.module.php');
$module = file_get_contents($root . '/Cockpit.module.php');
$styles = file_get_contents($root . '/assets/css/process-cockpit.css');
$scripts = file_get_contents($root . '/assets/js/process-cockpit.js');
if ($process === false || $module === false || $styles === false || $scripts === false) cockpitAdminUiFail('Unable to read admin UI assets.');

foreach (['overview', 'links', 'analytics', 'audit'] as $view) {
	if (strpos($process, "'{$view}'") === false) cockpitAdminUiFail("Missing admin view: {$view}.");
}
foreach (['uk-subnav uk-subnav-pill cockpit-admin-nav-list', 'uk-button uk-button-default', 'uk-table', 'uk-progress'] as $primitive) {
	if (strpos($process, $primitive) === false) cockpitAdminUiFail("Missing ProcessWire/UIkit primitive: {$primitive}.");
}
foreach (['pw-module-workspace', 'cockpit-page-intro', 'cockpit-metric-grid', 'pw-filter-panel', 'pw-table-panel', 'pw-empty-state', 'cockpit-insight-grid', 'cockpit-section'] as $workspacePrimitive) {
	if (strpos($process, $workspacePrimitive) === false) cockpitAdminUiFail("Missing design-system workspace primitive: {$workspacePrimitive}.");
}
foreach (['InputfieldForm', 'InputfieldText', 'InputfieldURL', 'InputfieldSelect', 'InputfieldCheckbox', 'InputfieldSubmit'] as $inputfieldClass) {
	if (strpos($process, "get('{$inputfieldClass}')") === false) cockpitAdminUiFail("Link editor is missing native {$inputfieldClass}.");
}
foreach (['cockpit-line-chart', 'cockpit-donut-chart', 'role="img"', 'data-points'] as $chartBoundary) {
	if (strpos($process, $chartBoundary) === false) cockpitAdminUiFail("Missing chart boundary: {$chartBoundary}.");
}
foreach (['Traffic filters', 'Quick periods', 'date_from', 'date_to', 'Previous period', 'cockpit-period-strip', 'cockpit-analytics-grid'] as $analyticsBoundary) {
	if (strpos($process . $styles, $analyticsBoundary) === false) cockpitAdminUiFail("Missing rich analytics boundary: {$analyticsBoundary}.");
}
foreach (['cockpit-filter-scope', 'cockpit-analytics-summary', 'number_format($percentage, 1)', 'aspect-ratio: 1'] as $analyticsUxBoundary) {
	if (strpos($process . $styles, $analyticsUxBoundary) === false) cockpitAdminUiFail("Missing analytics UX boundary: {$analyticsUxBoundary}.");
}
foreach (["'active_links'", "'disabled_links'", 'cockpit-top-links', "'View statistics'", "'last_hit_at'"] as $dashboardUxBoundary) {
	if (strpos($process . $module . $styles, $dashboardUxBoundary) === false) cockpitAdminUiFail("Missing dashboard UX boundary: {$dashboardUxBoundary}.");
}
foreach (['renderQuickCreate', 'cockpit-quick-create-form', 'return_view', "'Quick create'", "'Link ready'"] as $quickCreateBoundary) {
	if (strpos($process . $styles, $quickCreateBoundary) === false) cockpitAdminUiFail("Missing dashboard quick-create boundary: {$quickCreateBoundary}.");
}
if (strpos($scripts, "classList.add('cockpit-admin-page')") === false || strpos($styles, 'html.cockpit-admin-page body { overflow-x: hidden; }') === false || strpos($styles, '.cockpit-top-links { max-width: 100%; overflow: hidden; }') === false) {
	cockpitAdminUiFail('Dashboard table is missing mobile overflow containment.');
}
if (strpos($scripts, 'Math.max(240') !== false || strpos($scripts, 'Math.max(180') !== false) {
	cockpitAdminUiFail('Canvas minimum dimensions would distort responsive charts.');
}
foreach (['renderQrPanel', '?view=links&qr=', 'Download SVG', 'Generated by FieldtypeQRCode', 'cockpit-qr-layout'] as $qrBoundary) {
	if (strpos($process . $styles, $qrBoundary) === false) cockpitAdminUiFail("Missing QR admin boundary: {$qrBoundary}.");
}
foreach (['renderIconButton', "'copy'", "'edit'", "'statistics'", "'qr'", "'delete'", 'cockpit-icon-button', 'aria-label=', 'focus-visible'] as $actionBoundary) {
	if (strpos($process . $styles, $actionBoundary) === false) cockpitAdminUiFail("Missing accessible icon-action boundary: {$actionBoundary}.");
}
foreach (['--pw-text-color', '--pw-border-color', '--pw-primary-color', '--pw-blocks-background'] as $themeVariable) {
	if (strpos($styles, $themeVariable) === false) cockpitAdminUiFail("Missing ProcessWire theme variable: {$themeVariable}.");
}
foreach (['--cockpit-space-xs', '--cockpit-space-sm', '--cockpit-space-md', '--cockpit-space-lg', '--cockpit-space-xl'] as $spacingToken) {
	if (strpos($styles, $spacingToken) === false) cockpitAdminUiFail("Missing Tickets-compatible spacing token: {$spacingToken}.");
}
if (strpos($styles, '--pw-spacing') !== false) cockpitAdminUiFail('Undefined --pw-spacing token reintroduced.');
if (strpos($process, 'cockpit-admin-settings') === false || strpos($process, 'uk-subnav uk-subnav-pill cockpit-admin-nav-list') === false) {
	cockpitAdminUiFail('Primary navigation must use the Tickets-style pill navigation and separate settings control.');
}
if (strpos($process, 'uk-tab pw-module-tabs') !== false) cockpitAdminUiFail('Legacy tab navigation reintroduced.');
if (strpos($styles, '.ProcessCockpit.cockpit-workspace') === false) cockpitAdminUiFail('Custom CSS is not scoped to the Cockpit workspace.');
foreach (['.cockpit-admin > * { min-width: 0; }', '@media (max-width: 639px)', '.cockpit-table-panel table', '.cockpit-admin-nav-list'] as $responsiveBoundary) {
	if (strpos($styles, $responsiveBoundary) === false) cockpitAdminUiFail("Missing responsive containment boundary: {$responsiveBoundary}.");
}
foreach (['eval(', 'new Function(', 'document.write(', 'http://', 'https://'] as $forbiddenScript) {
	if (strpos($scripts, $forbiddenScript) !== false) cockpitAdminUiFail("Forbidden script construct: {$forbiddenScript}.");
}
if (strpos($scripts, 'drawLineChart') === false || strpos($scripts, 'drawDonutChart') === false) {
	cockpitAdminUiFail('Dependency-free chart renderers are missing.');
}
foreach ([
	"\$section(\$this->_('Links')",
	"\$section(\$this->_('Routing')",
	"\$section(\$this->_('Analytics')",
	"\$section(\$this->_('Integrations')",
	"\$section(\$this->_('Data & privacy')",
	"Inputfield::skipLabelHeader",
	"Inputfield::collapsedYes",
	"'warning' : 'primary'",
	"'danger'",
] as $configBoundary) {
	if (strpos($module, $configBoundary) === false) cockpitAdminUiFail("Missing config UI boundary: {$configBoundary}.");
}
if (substr_count($process, 'collapse_info=1') < 3) cockpitAdminUiFail('Cockpit settings links do not collapse module information consistently.');
foreach ([
	'configurePageChrome($view, $editingId > 0)',
	"'overview' => [\$this->_('Dashboard'), '']",
	"\$this->breadcrumb(\$baseUrl, \$this->_('Cockpit'))",
	"\$this->browserTitle(sprintf(\$this->_('%s — Cockpit'), \$label))",
] as $pageChromeBoundary) {
	if (strpos($process, $pageChromeBoundary) === false) cockpitAdminUiFail("Missing page chrome boundary: {$pageChromeBoundary}.");
}
foreach ([
	'configureSettingsPageChrome()',
	"\$process->headline(\$this->_('Cockpit settings'))",
	"\$process->breadcrumb(\$workspaceUrl, \$this->_('Cockpit'))",
	"\$process->breadcrumb(\$settingsUrl, \$this->_('Settings'))",
] as $settingsChromeBoundary) {
	if (strpos($module, $settingsChromeBoundary) === false) cockpitAdminUiFail("Missing settings chrome boundary: {$settingsChromeBoundary}.");
}

echo "Admin UI static tests passed\n";
